### ISSUE TITLE
ERROR: Bad key override in Chef::NodeMap filter expression

### ISSUE THREAD

**Issue by rj-reilly** [irvingpop/fancy_execute#4]
Hi, Getting the following error:

```
Recipe Compile Error in /var/chef/cache/cookbooks/fancy_execute/libraries/fancy_execute_provider.rb
================================================================================

RuntimeError
------------
Bad key override in Chef::NodeMap filter expression

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/fancy_execute/libraries/fancy_execute_provider.rb:27:in `<class:FancyExecute>'
  /var/chef/cache/cookbooks/fancy_execute/libraries/fancy_execute_provider.rb:24:in `<class:Provider>'
  /var/chef/cache/cookbooks/fancy_execute/libraries/fancy_execute_provider.rb:23:in `<class:Chef>'
  /var/chef/cache/cookbooks/fancy_execute/libraries/fancy_execute_provider.rb:22:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/fancy_execute/libraries/fancy_execute_provider.rb:

 20:  require 'chef/provider'
 21:
 22:  class Chef
 23:    class Provider
 24:      class FancyExecute < Chef::Provider::Execute
 25:
 26:        # this code will only work with Chef 12.4+
 27>>       provides :execute, override: true
 28:
 29:        # force this to on if not set
 30:        Chef::Config[:live_stream] ||= true
 31:
 32:        def opts
 33:          opts = {}
 34:          opts[:timeout]     = timeout
 35:          opts[:returns]     = returns if returns
 36:          opts[:environment] = environment if environment


Running handlers:
[2016-02-08T09:57:03-05:00] ERROR: Running exception handlers
Running handlers complete
[2016-02-08T09:57:03-05:00] ERROR: Exception handlers complete
[2016-02-08T09:57:03-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 3.15900876 seconds
[2016-02-08T09:57:03-05:00] ERROR: Bad key override in Chef::NodeMap filter expression
[2016-02-08T09:57:03-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by irvingpop** [comment]
hey @devilldog  I'm guessing you're running this with a version of Chef that's either too old (see the comment on the line above) or too new (12.6.0 bakes this feature in).

**Comment by irvingpop** [comment]
Closing this out in favor of:  https://github.com/chef/chef/commit/c03d49c7cc3b5eb351abc9f6537a1a65692e93fc
