### ISSUE TITLE
Seems to break with chef-client 13.0.113

### ISSUE THREAD

**Issue by vinyar** [irvingpop/fancy_execute#6]
Note, used via supermarket-omnibus-cookbook
Works fine with latest build of 12.x client.

workstation config:
```
Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 5.6.2
kitchen version: 1.15.0
```

Output via 13.0.113:
```
$ kitchen converge               [ruby-2.3.1p112]
-----> Starting Kitchen (v1.15.0)
-----> Converging <default-ubuntu-1604>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.6.2...
       Removing non-cookbook files before transfer
       Preparing solo.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-ubuntu-1604>
       Starting Chef Client, version 13.0.113
       resolving cookbooks for run list: ["syseng_chefsrv::supermarket"]
       Synchronizing Cookbooks:
         - syseng_chefsrv (0.1.0)
         - hostsfile (2.4.5)
         - chef-ingredient (2.0.1)
         - supermarket-omnibus-cookbook (2.0.1)
         - fancy_execute (1.0.2)
         - compat_resource (12.16.3)
       Installing Cookbook Gems:
       Compiling Cookbooks...

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/fancy_execute/libraries/fancy_execute_provider.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `set' for Chef::Platform:Class

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/fancy_execute/libraries/fancy_execute_provider.rb:64:in `block in <top (required)>'
         /tmp/kitchen/cache/cookbooks/fancy_execute/libraries/fancy_execute_provider.rb:63:in `each'
         /tmp/kitchen/cache/cookbooks/fancy_execute/libraries/fancy_execute_provider.rb:63:in `<top (required)>'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/fancy_execute/libraries/fancy_execute_provider.rb:

        57:
        58:      end
        59:    end
        60:  end
        61:
        62:  # Set FancyExecute as the default provider for :execute on Linux platforms
        63:  %w(debian ubuntu fedora redhat centos).each do |platform|
        64>>   Chef::Platform.set plaform: platform.to_sym, resource: :execute, provider: Chef::Provider::FancyExecute
        65:  end
        66:

       System Info:
       ------------
       chef_version=13.0.113
       platform=ubuntu
       platform_version=16.04
       ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
       program_name=chef-solo worker: ppid=3637;start=21:17:37;
       executable=/opt/chef/bin/chef-solo


       Running handlers:
       [2017-04-10T21:17:38+00:00] ERROR: Running exception handlers
       [2017-04-10T21:17:38+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-04-10T21:17:38+00:00] ERROR: Exception handlers complete
       [2017-04-10T21:17:38+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 01 seconds
       [2017-04-10T21:17:38+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-04-10T21:17:38+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-04-10T21:17:38+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-04-10T21:17:38+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-04-10T21:17:38+00:00] ERROR: undefined method `set' for Chef::Platform:Class
       [2017-04-10T21:17:38+00:00] ERROR: undefined method `set' for Chef::Platform:Class
       [2017-04-10T21:17:38+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-04-10T21:17:38+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by irvingpop** [comment]
fixed by #7
